version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: geo-tasks
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - 4000:4000

  db:
    image: postgis/postgis:13-master
    environment:
      POSTGRES_DB: geo_tasks_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data